variable "env" {}
variable "tags" {}
variable "component" {}
variable "vpc_id" {}
variable "sg_ingress_cidr" {}
variable "ssh_ingress_cidr" {}
variable "port" {}
variable "instance_type" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
variable "subnet_ids" {}
variable "zone_id" {}
variable "priority" {}
variable "private_alb_name" {}
variable "private_listener" {}
variable "public_alb_name" {}
variable "public_listener" {}
variable "default_vpc_id" {}

